/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as InspectIdRouteImport } from './routes/inspect.$id'
import { Route as InspectIdReviewRouteImport } from './routes/inspect.$id_.review'
import { Route as ReportInspectionIdRouteImport } from './routes/report.$inspectionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectIdRoute = InspectIdRouteImport.update({
  id: '/inspect/$id',
  path: '/inspect/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectIdReviewRoute = InspectIdReviewRouteImport.update({
  id: '/inspect/$id_/review',
  path: '/inspect/$id/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportInspectionIdRoute = ReportInspectionIdRouteImport.update({
  id: '/report/$inspectionId',
  path: '/report/$inspectionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/reports': typeof ReportsRoute
  '/inspect/$id': typeof InspectIdRoute
  '/inspect/$id/review': typeof InspectIdReviewRoute
  '/report/$inspectionId': typeof ReportInspectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/reports': typeof ReportsRoute
  '/inspect/$id': typeof InspectIdRoute
  '/inspect/$id/review': typeof InspectIdReviewRoute
  '/report/$inspectionId': typeof ReportInspectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/reports': typeof ReportsRoute
  '/inspect/$id': typeof InspectIdRoute
  '/inspect/$id_/review': typeof InspectIdReviewRoute
  '/report/$inspectionId': typeof ReportInspectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/reports'
    | '/inspect/$id'
    | '/inspect/$id/review'
    | '/report/$inspectionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/reports'
    | '/inspect/$id'
    | '/inspect/$id/review'
    | '/report/$inspectionId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/settings'
    | '/reports'
    | '/inspect/$id'
    | '/inspect/$id_/review'
    | '/report/$inspectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  ReportsRoute: typeof ReportsRoute
  InspectIdRoute: typeof InspectIdRoute
  InspectIdReviewRoute: typeof InspectIdReviewRoute
  ReportInspectionIdRoute: typeof ReportInspectionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspect/$id': {
      id: '/inspect/$id'
      path: '/inspect/$id'
      fullPath: '/inspect/$id'
      preLoaderRoute: typeof InspectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspect/$id_/review': {
      id: '/inspect/$id_/review'
      path: '/inspect/$id/review'
      fullPath: '/inspect/$id/review'
      preLoaderRoute: typeof InspectIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$inspectionId': {
      id: '/report/$inspectionId'
      path: '/report/$inspectionId'
      fullPath: '/report/$inspectionId'
      preLoaderRoute: typeof ReportInspectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  ReportsRoute: ReportsRoute,
  InspectIdRoute: InspectIdRoute,
  InspectIdReviewRoute: InspectIdReviewRoute,
  ReportInspectionIdRoute: ReportInspectionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
