/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as InspectIdRouteImport } from './routes/inspect.$id'
import { Route as InspectIdReviewRouteImport } from './routes/inspect.$id_.review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectIdRoute = InspectIdRouteImport.update({
  id: '/inspect/$id',
  path: '/inspect/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectIdReviewRoute = InspectIdReviewRouteImport.update({
  id: '/inspect/$id_/review',
  path: '/inspect/$id/review',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/inspect/$id': typeof InspectIdRoute
  '/inspect/$id/review': typeof InspectIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/inspect/$id': typeof InspectIdRoute
  '/inspect/$id/review': typeof InspectIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/inspect/$id': typeof InspectIdRoute
  '/inspect/$id_/review': typeof InspectIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/settings' | '/inspect/$id' | '/inspect/$id/review'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/inspect/$id' | '/inspect/$id/review'
  id: '__root__' | '/' | '/settings' | '/inspect/$id' | '/inspect/$id_/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  InspectIdRoute: typeof InspectIdRoute
  InspectIdReviewRoute: typeof InspectIdReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspect/$id': {
      id: '/inspect/$id'
      path: '/inspect/$id'
      fullPath: '/inspect/$id'
      preLoaderRoute: typeof InspectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspect/$id_/review': {
      id: '/inspect/$id_/review'
      path: '/inspect/$id/review'
      fullPath: '/inspect/$id/review'
      preLoaderRoute: typeof InspectIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  InspectIdRoute: InspectIdRoute,
  InspectIdReviewRoute: InspectIdReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
