import type { InspectionValues } from "./types";

/**
 * Design / Style presets for Queensland / Australian residential stock.
 * Single primary values only. Existing answers are never overwritten.
 */
export const DESIGN_PRESETS: Record<string, InspectionValues> = {
  Queenslander: {
    imp_highset: true,
    imp_units: "1",
    foundations: ["found_timber_stumps"],
    floor_structure: ["floor_struct_timber"],
    wall_framing_type: "Timber hardwood",
    roof_framing_type: "Timber rafters conventional",
    ext: ["ext_timber_weatherboard"],
    rc: ["rc_corrugated"],
    rd: ["rd_metal"],
    il: ["il_vj", "il_likely_asbestos"],
    ceil: ["ceil_vj_timber", "ceil_likely_asbestos"],
    flr: ["flr_solid_timber", "flr_polished"],
    ceil_heights_type: "3.0 metres",
    light: ["light_mixed"],
    accom: ["accom_front_verandah"],
    vent: ["vent_subfloor"],
    fire: ["fire_conventional_alarm"],
    bath_tiles_type: "Ceramic tiles",
    bath_floor: "Ceramic tiles",
    bath_surround: "Ceramic tiles",
    am: ["am_bir"],
  },

  "Highset Queenslander": {
    imp_highset: true,
    imp_units: "1",
    foundations: ["found_timber_stumps"],
    floor_structure: ["floor_struct_timber"],
    wall_framing_type: "Timber hardwood",
    roof_framing_type: "Timber rafters conventional",
    ext: ["ext_timber_weatherboard"],
    rc: ["rc_corrugated"],
    rd: ["rd_metal"],
    il: ["il_vj", "il_likely_asbestos"],
    ceil: ["ceil_vj_timber", "ceil_likely_asbestos"],
    flr: ["flr_solid_timber", "flr_polished"],
    ceil_heights_type: "3.0 metres",
    light: ["light_mixed"],
    accom: ["accom_front_verandah"],
    vent: ["vent_subfloor"],
    fire: ["fire_conventional_alarm"],
    bath_tiles_type: "Ceramic tiles",
    bath_floor: "Ceramic tiles",
    bath_surround: "Ceramic tiles",
    am: ["am_bir"],
  },

  Ashgrovian: {
    imp_highset: true,
    imp_units: "1",
    foundations: ["found_timber_stumps"],
    floor_structure: ["floor_struct_timber"],
    wall_framing_type: "Timber hardwood",
    roof_framing_type: "Timber rafters conventional",
    ext: ["ext_timber_weatherboard"],
    rc: ["rc_corrugated"],
    rd: ["rd_metal"],
    il: ["il_vj", "il_likely_asbestos"],
    ceil: ["ceil_plasterboard", "ceil_likely_asbestos"],
    flr: ["flr_solid_timber", "flr_polished"],
    ceil_heights_type: "3.0 metres",
    light: ["light_mixed"],
    accom: ["accom_front_verandah"],
    vent: ["vent_subfloor"],
    fire: ["fire_conventional_alarm"],
    bath_tiles_type: "Ceramic tiles",
    bath_floor: "Ceramic tiles",
    bath_surround: "Ceramic tiles",
    am: ["am_bir"],
  },

  "Workers Cottage": {
    imp_lowset: true,
    imp_units: "1",
    foundations: ["found_timber_stumps"],
    floor_structure: ["floor_struct_timber"],
    wall_framing_type: "Timber softwood",
    roof_framing_type: "Timber rafters conventional",
    ext: ["ext_timber_weatherboard"],
    rc: ["rc_corrugated"],
    rd: ["rd_metal"],
    il: ["il_vj", "il_likely_asbestos"],
    ceil: ["ceil_timber", "ceil_likely_asbestos"],
    flr: ["flr_solid_timber", "flr_pine", "flr_polished"],
    ceil_heights_type: "3.0 metres",
    light: ["light_mixed"],
    accom: ["accom_front_verandah"],
    vent: ["vent_subfloor"],
    fire: ["fire_conventional_alarm"],
    bath_tiles_type: "Ceramic tiles",
    bath_floor: "Ceramic tiles",
    bath_surround: "Ceramic tiles",
    am: ["am_bir"],
  },

  Colonial: {
    imp_highset: true,
    imp_units: "1",
    foundations: ["found_timber_stumps"],
    floor_structure: ["floor_struct_timber"],
    wall_framing_type: "Timber hardwood",
    roof_framing_type: "Timber rafters conventional",
    ext: ["ext_timber_weatherboard"],
    rc: ["rc_corrugated"],
    rd: ["rd_metal"],
    il: ["il_timber", "il_likely_asbestos"],
    ceil: ["ceil_timber", "ceil_likely_asbestos"],
    flr: ["flr_solid_timber", "flr_polished"],
    ceil_heights_type: "3.0 metres",
    light: ["light_mixed"],
    accom: ["accom_front_verandah"],
    fire: ["fire_conventional_alarm"],
    bath_tiles_type: "Ceramic tiles",
    bath_floor: "Ceramic tiles",
    bath_surround: "Ceramic tiles",
    am: ["am_bir"],
  },

  Victorian: {
    imp_highset: true,
    imp_units: "1",
    foundations: ["found_timber_stumps"],
    floor_structure: ["floor_struct_timber"],
    wall_framing_type: "Timber hardwood",
    roof_framing_type: "Timber rafters conventional",
    ext: ["ext_timber_weatherboard"],
    rc: ["rc_corrugated"],
    rd: ["rd_metal"],
    il: ["il_timber", "il_likely_asbestos"],
    ceil: ["ceil_plasterboard", "ceil_likely_asbestos"],
    flr: ["flr_solid_timber", "flr_polished"],
    ceil_heights_type: "3.5 metres",
    light: ["light_mixed"],
    accom: ["accom_front_verandah"],
    vent: ["vent_subfloor"],
    fire: ["fire_conventional_alarm"],
    bath_tiles_type: "Ceramic tiles",
    bath_floor: "Ceramic tiles",
    bath_surround: "Ceramic tiles",
    am: ["am_bir"],
  },

  Federation: {
    imp_highset: true,
    imp_units: "1",
    foundations: ["found_timber_stumps"],
    floor_structure: ["floor_struct_timber"],
    wall_framing_type: "Timber hardwood",
    roof_framing_type: "Timber rafters conventional",
    ext: ["ext_timber_weatherboard"],
    rc: ["rc_terracotta"],
    rd: ["rd_metal"],
    il: ["il_timber", "il_likely_asbestos"],
    ceil: ["ceil_plasterboard", "ceil_likely_asbestos"],
    flr: ["flr_solid_timber", "flr_polished"],
    ceil_heights_type: "3.0 metres",
    light: ["light_mixed"],
    accom: ["accom_front_verandah"],
    vent: ["vent_subfloor"],
    fire: ["fire_conventional_alarm"],
    bath_tiles_type: "Ceramic tiles",
    bath_floor: "Ceramic tiles",
    bath_surround: "Ceramic tiles",
    am: ["am_bir"],
  },

  "Federation Filigree": {
    imp_highset: true,
    imp_units: "1",
    foundations: ["found_timber_stumps"],
    floor_structure: ["floor_struct_timber"],
    wall_framing_type: "Timber hardwood",
    roof_framing_type: "Timber rafters conventional",
    ext: ["ext_timber_weatherboard"],
    rc: ["rc_corrugated"],
    rd: ["rd_metal"],
    il: ["il_timber", "il_likely_asbestos"],
    ceil: ["ceil_plasterboard", "ceil_likely_asbestos"],
    flr: ["flr_solid_timber", "flr_polished"],
    ceil_heights_type: "3.0 metres",
    light: ["light_mixed"],
    accom: ["accom_front_verandah"],
    vent: ["vent_subfloor"],
    fire: ["fire_conventional_alarm"],
    bath_tiles_type: "Ceramic tiles",
    bath_floor: "Ceramic tiles",
    bath_surround: "Ceramic tiles",
    am: ["am_bir"],
  },

  "Federation Bungalow": {
    imp_lowset: true,
    imp_units: "1",
    foundations: ["found_timber_stumps"],
    floor_structure: ["floor_struct_timber"],
    wall_framing_type: "Timber hardwood",
    roof_framing_type: "Timber rafters conventional",
    ext: ["ext_timber_weatherboard"],
    rc: ["rc_terracotta"],
    rd: ["rd_metal"],
    il: ["il_timber", "il_likely_asbestos"],
    ceil: ["ceil_plasterboard", "ceil_likely_asbestos"],
    flr: ["flr_solid_timber", "flr_polished"],
    ceil_heights_type: "3.0 metres",
    light: ["light_mixed"],
    accom: ["accom_front_verandah"],
    vent: ["vent_subfloor"],
    fire: ["fire_conventional_alarm"],
    bath_tiles_type: "Ceramic tiles",
    bath_floor: "Ceramic tiles",
    bath_surround: "Ceramic tiles",
    am: ["am_bir"],
  },

  Interwar: {
    imp_lowset: true,
    imp_units: "1",
    foundations: ["found_concrete_stumps"],
    floor_structure: ["floor_struct_timber"],
    wall_framing_type: "Timber softwood",
    roof_framing_type: "Timber rafters conventional",
    ext: ["ext_timber_weatherboard"],
    rc: ["rc_corrugated"],
    rd: ["rd_metal"],
    il: ["il_plasterboard", "il_likely_asbestos"],
    ceil: ["ceil_plasterboard", "ceil_likely_asbestos"],
    flr: ["flr_solid_timber", "flr_polished"],
    ceil_heights_type: "3.0 metres",
    light: ["light_mixed"],
    vent: ["vent_subfloor"],
    fire: ["fire_conventional_alarm"],
    bath_tiles_type: "Ceramic tiles",
    bath_floor: "Ceramic tiles",
    bath_surround: "Ceramic tiles",
    am: ["am_bir"],
  },

  "Art Deco": {
    imp_lowset: true,
    imp_units: "1",
    foundations: ["found_concrete_stumps"],
    floor_structure: ["floor_struct_timber"],
    wall_framing_type: "Timber softwood",
    roof_framing_type: "Timber rafters conventional",
    ext: ["ext_rendered_cement"],
    rc: ["rc_terracotta"],
    rd: ["rd_metal"],
    il: ["il_plasterboard", "il_likely_asbestos"],
    ceil: ["ceil_plasterboard", "ceil_likely_asbestos"],
    flr: ["flr_solid_timber", "flr_polished"],
    ceil_heights_type: "3.0 metres",
    light: ["light_mixed"],
    fire: ["fire_conventional_alarm"],
    bath_tiles_type: "Ceramic tiles",
    bath_floor: "Ceramic tiles",
    bath_surround: "Ceramic tiles",
    am: ["am_bir"],
  },

  "Post-war Timber": {
    imp_lowset: true,
    imp_units: "1",
    foundations: ["found_concrete_stumps"],
    floor_structure: ["floor_struct_timber"],
    wall_framing_type: "Timber softwood",
    roof_framing_type: "Timber trusses",
    ext: ["ext_timber_weatherboard"],
    rc: ["rc_corrugated"],
    rd: ["rd_metal"],
    il: ["il_plasterboard", "il_likely_asbestos"],
    ceil: ["ceil_plasterboard", "ceil_likely_asbestos"],
    flr: ["flr_solid_timber", "flr_polished"],
    ceil_heights_type: "Typical",
    light: ["light_mixed"],
    fire: ["fire_conventional_alarm"],
    bath_tiles_type: "Ceramic tiles",
    bath_floor: "Ceramic tiles",
    bath_surround: "Ceramic tiles",
    kit_feat: ["kit_gas"],
    am: ["am_bir"],
  },

  "Post-war Brick": {
    imp_lowset: true,
    imp_units: "1",
    foundations: ["found_concrete_slab"],
    floor_structure: ["floor_struct_concrete"],
    wall_framing_type: "Timber softwood",
    roof_framing_type: "Timber trusses",
    ext: ["ext_brick_veneer"],
    rc: ["rc_concrete_tiles"],
    rd: ["rd_metal"],
    il: ["il_plasterboard", "il_likely_asbestos"],
    ceil: ["ceil_plasterboard", "ceil_likely_asbestos"],
    flr: ["flr_carpet", "flr_polished"],
    ceil_heights_type: "Typical",
    light: ["light_mixed"],
    fire: ["fire_conventional_alarm"],
    bath_tiles_type: "Ceramic tiles",
    bath_floor: "Ceramic tiles",
    bath_surround: "Ceramic tiles",
    kit_feat: ["kit_gas"],
    am: ["am_bir"],
  },

  "Mid-century Modern": {
    imp_lowset: true,
    imp_units: "1",
    foundations: ["found_concrete_slab"],
    floor_structure: ["floor_struct_concrete"],
    wall_framing_type: "Timber softwood",
    roof_framing_type: "Timber trusses",
    ext: ["ext_brick_veneer"],
    rc: ["rc_concrete_tiles"],
    rd: ["rd_metal"],
    il: ["il_plasterboard"],
    ceil: ["ceil_plasterboard"],
    flr: ["flr_solid_timber"],
    ceil_heights_type: "Typical",
    light: ["light_mixed"],
    fire: ["fire_conventional_alarm"],
    bath_tiles_type: "Ceramic tiles",
    bath_floor: "Ceramic tiles",
    bath_surround: "Ceramic tiles",
    am: ["am_bir"],
  },

  "Brick and Tile": {
    imp_lowset: true,
    imp_units: "1",
    foundations: ["found_concrete_slab"],
    floor_structure: ["floor_struct_concrete"],
    wall_framing_type: "Timber softwood",
    roof_framing_type: "Timber trusses",
    ext: ["ext_brick_veneer"],
    rc: ["rc_concrete_tiles"],
    rd: ["rd_metal"],
    il: ["il_plasterboard"],
    ceil: ["ceil_plasterboard"],
    flr: ["flr_carpet"],
    ceil_heights_type: "Typical",
    light: ["light_mixed"],
    fire: ["fire_conventional_alarm"],
    bath_tiles_type: "Ceramic tiles",
    bath_floor: "Ceramic tiles",
    bath_surround: "Ceramic tiles",
    kit_feat: ["kit_gas"],
    am: ["am_bir"],
  },

  Contemporary: {
    imp_lowset: true,
    imp_units: "1",
    foundations: ["found_concrete_slab"],
    floor_structure: ["floor_struct_concrete"],
    wall_framing_type: "Timber softwood",
    roof_framing_type: "Timber trusses",
    ext: ["ext_brick_veneer"],
    rc: ["rc_colorbond"],
    rd: ["rd_metal"],
    il: ["il_plasterboard"],
    ceil: ["ceil_plasterboard"],
    flr: ["flr_engineered"],
    ceil_heights_type: "2.7 metres",
    light: ["light_mixed"],
    vent: ["hvac_split_multi"],
    fire: ["fire_conventional_alarm"],
    kit_feat: ["kit_induction"],
    app: ["app_bosch"],
    bath_tiles_type: "Large format porcelain",
    bath_floor: "Porcelain tiles",
    bath_surround: "Porcelain tiles",
    bath_feat: ["bath_frameless"],
    am: ["am_bir"],
  },

  Hamptons: {
    imp_lowset: true,
    imp_units: "1",
    foundations: ["found_concrete_slab"],
    floor_structure: ["floor_struct_concrete"],
    wall_framing_type: "Timber softwood",
    roof_framing_type: "Timber trusses",
    ext: ["ext_fc_weatherboard"],
    rc: ["rc_colorbond"],
    rd: ["rd_metal"],
    il: ["il_plasterboard"],
    ceil: ["ceil_plasterboard"],
    flr: ["flr_engineered"],
    ceil_heights_type: "3.0 metres",
    light: ["light_mixed"],
    vent: ["hvac_ducted_heating_ac"],
    fire: ["fire_conventional_alarm"],
    kit_feat: ["kit_softclose"],
    app: ["app_fisherpaykel"],
    bath_tiles_type: "Large format porcelain",
    bath_floor: "Porcelain tiles",
    bath_surround: "Porcelain tiles",
    bath_feat: ["bath_freestanding"],
    am: ["am_wir"],
    accom: ["accom_front_verandah"],
  },

  Coastal: {
    imp_lowset: true,
    imp_units: "1",
    foundations: ["found_concrete_slab"],
    floor_structure: ["floor_struct_concrete"],
    wall_framing_type: "Timber softwood",
    roof_framing_type: "Timber trusses",
    ext: ["ext_fc_weatherboard"],
    rc: ["rc_colorbond"],
    rd: ["rd_metal"],
    il: ["il_plasterboard"],
    ceil: ["ceil_plasterboard"],
    flr: ["flr_engineered"],
    ceil_heights_type: "2.7 metres",
    light: ["light_mixed"],
    vent: ["hvac_split_multi"],
    fire: ["fire_conventional_alarm"],
    kit_feat: ["kit_induction"],
    app: ["app_fisherpaykel"],
    bath_tiles_type: "Large format porcelain",
    bath_floor: "Porcelain tiles",
    bath_surround: "Porcelain tiles",
    bath_feat: ["bath_frameless"],
    am: ["am_bir"],
  },

  "Acreage or Rural": {
    imp_lowset: true,
    imp_units: "1",
    foundations: ["found_concrete_slab"],
    floor_structure: ["floor_struct_concrete"],
    wall_framing_type: "Timber softwood",
    roof_framing_type: "Timber trusses",
    ext: ["ext_brick_veneer"],
    rc: ["rc_colorbond"],
    rd: ["rd_metal"],
    il: ["il_plasterboard"],
    ceil: ["ceil_plasterboard"],
    flr: ["flr_engineered"],
    ceil_heights_type: "2.7 metres",
    light: ["light_mixed"],
    vent: ["hvac_split_multi"],
    fire: ["fire_conventional_alarm"],
    bath_tiles_type: "Ceramic tiles",
    bath_floor: "Ceramic tiles",
    bath_surround: "Ceramic tiles",
    am: ["am_bir"],
  },

  "Townhouse or Terrace": {
    imp_lowset: true,
    imp_units: "1",
    foundations: ["found_concrete_slab"],
    floor_structure: ["floor_struct_concrete"],
    wall_framing_type: "Timber softwood",
    roof_framing_type: "Timber trusses",
    ext: ["ext_brick_veneer"],
    rc: ["rc_colorbond"],
    rd: ["rd_metal"],
    il: ["il_plasterboard"],
    ceil: ["ceil_plasterboard"],
    flr: ["flr_engineered"],
    ceil_heights_type: "2.7 metres",
    light: ["light_mixed"],
    vent: ["hvac_split_single"],
    fire: ["fire_conventional_alarm"],
    bath_tiles_type: "Porcelain tiles",
    bath_floor: "Porcelain tiles",
    bath_surround: "Porcelain tiles",
    am: ["am_bir"],
  },
};

export function isUnset(value: InspectionValues[string]): boolean {
  if (value === undefined || value === null) return true;
  if (typeof value === "string") return value.trim() === "";
  if (Array.isArray(value)) return value.length === 0;
  return false;
}

export function applyDesignPreset(
  current: InspectionValues,
  design: string,
): InspectionValues {
  const preset = DESIGN_PRESETS[design];
  if (!preset) return current;

  let next = current;
  let changed = false;

  for (const [key, presetValue] of Object.entries(preset)) {
    if (Array.isArray(presetValue)) {
      const existing = Array.isArray(current[key]) ? (current[key] as string[]) : [];
      const toAdd = presetValue.filter((id) => !existing.includes(id));
      if (toAdd.length === 0) continue;
      if (!changed) {
        next = { ...current };
        changed = true;
      }
      next[key] = [...existing, ...toAdd];
      continue;
    }

    if (!isUnset(current[key])) continue;
    if (!changed) {
      next = { ...current };
      changed = true;
    }
    next[key] = presetValue;
  }

  return next;
}
